services:
  loadbalancer:
    image: nginx:1.27.5-alpine

    ports:
      - 80:80

    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  web:
    container_name: exam-solver-backend-web
    build:
      context: .

    ports:
      - 8000:8000

    env_file:
      - .env

  worker:
    container_name: exam-solver-backend-worker
    build:
      context: .

    command: "uv run celery -A core worker -l INFO"

    depends_on:
      - rabbitmq

    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:3.13.7-management-alpine
    ports:
      - 5672:5672
      - 15672:15672

    environment:
      - RABBITMQ_DEFAULT_USER=${BROKER_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${BROKER_DEFAULT_PASSWORD}

    volumes:
      - ./.data/rabbitmq:/var/lib/rabbitmq
