services:
  db:
    image: postgres:16.3-alpine
    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

    env_file:
      - .env

    volumes:
      - ./.data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:7.4.2-alpine
    ports:
      - 6379:6379

    volumes:
      - ./.data/redis:/data

    env_file:
      - .env
