# Generated by Django 5.2.1 on 2025-06-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_exam_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='by_pass_is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
