# Generated by Django 5.2.1 on 2025-06-11 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_exam_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='input_document',
            field=models.TextField(blank=True, null=True),
        ),
    ]
