# Generated by Django 5.2.1 on 2025-06-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_exam_input_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
